services:
  web:
    build: .
    image: pygoat
    command: python3 manage.py runserver 
    ports:
     - "8000:8000"
    volumes:
      - .:/opt/app
    depends_on:
      - migration
      - db
  migration:
    image: pygoat
    command: python3 manage.py migrate
    volumes:
      - .:/opt/app
    depends_on:
      - db
