name: DevSecOps Pipeline

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build_docker:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Check for Docker-relevant changes
          id: changes
          run: |
            git fetch origin master
            CHANGED=$(git diff --name-only origin/master HEAD)
            echo "$CHANGED"
            echo "changed=$CHANGED" >> $GITHUB_OUTPUT

        - name: Build Docker image
          if: |
            steps.changes.outputs.changed != '' &&
            (
              contains(steps.changes.outputs.changed, 'Dockerfile') ||
              contains(steps.changes.outputs.changed, 'requirements.txt') ||
              contains(steps.changes.outputs.changed, '.py')
            )
          run: docker build -t pygoat:latest .
    sca-security:
        name: SCA Scan (pip-audit + Snyk)
        runs-on: ubuntu-latest
        needs: build_docker

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set Up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Run pip-audit
              uses: pypa/gh-action-pip-audit@v1.1.0
              continue-on-error: true

            - name: Install Snyk CLI
              run: npm install -g snyk

            - name: Authenticate Snyk
              run: snyk auth ${{ secrets.SNYK_TOKEN }}

            - name: Run Snyk test (CLI)
              run: snyk test --file=requirements.txt --package-manager=pip
              continue-on-error: true

      